# -*- coding: utf-8 -*-
"""dhanush.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e0xOXaR_h2-IBRlDxpe2cqbwUDFDppju
"""

plt.figure(figsize=(10, 5))
plt.plot(y_actual[-20:], label='Actual', marker='o')
plt.plot(train_predict[-20:], label='Predicted', marker='x')
plt.title('L Plot ast 20 Predictions vs Actual')
plt.legend()
plt.grid(True)
plt.show()